// 영단어 데이터베이스 - 120개 단어
const WORDS = [
  // ===== BEGINNER (40 words) =====
  {
    id: 1,
    word: "happy",
    phonetic: "/ˈhæpi/",
    partOfSpeech: "adjective",
    definition: "Feeling or showing pleasure or contentment",
    korean: "행복한, 기쁜",
    example: "She was happy to see her old friend.",
    exampleKorean: "그녀는 오랜 친구를 만나서 기뻤어요.",
    synonyms: ["joyful", "glad", "pleased"],
    level: "beginner"
  },
  {
    id: 2,
    word: "beautiful",
    phonetic: "/ˈbjuːtɪfʊl/",
    partOfSpeech: "adjective",
    definition: "Pleasing the senses or mind aesthetically",
    korean: "아름다운, 예쁜",
    example: "The sunset was absolutely beautiful.",
    exampleKorean: "석양이 정말 아름다웠어요.",
    synonyms: ["gorgeous", "lovely", "stunning"],
    level: "beginner"
  },
  {
    id: 3,
    word: "friend",
    phonetic: "/frend/",
    partOfSpeech: "noun",
    definition: "A person whom one knows and with whom one has a bond of mutual affection",
    korean: "친구",
    example: "He is my best friend since childhood.",
    exampleKorean: "그는 어린 시절부터 나의 가장 친한 친구예요.",
    synonyms: ["companion", "pal", "buddy"],
    level: "beginner"
  },
  {
    id: 4,
    word: "travel",
    phonetic: "/ˈtrævəl/",
    partOfSpeech: "verb",
    definition: "To make a journey, typically of some length",
    korean: "여행하다",
    example: "I love to travel to new countries.",
    exampleKorean: "저는 새로운 나라로 여행하는 것을 좋아해요.",
    synonyms: ["journey", "tour", "voyage"],
    level: "beginner"
  },
  {
    id: 5,
    word: "learn",
    phonetic: "/lɜːrn/",
    partOfSpeech: "verb",
    definition: "Gain or acquire knowledge of or skill in something",
    korean: "배우다, 학습하다",
    example: "Children learn quickly when they are curious.",
    exampleKorean: "아이들은 호기심이 있을 때 빠르게 배워요.",
    synonyms: ["study", "acquire", "grasp"],
    level: "beginner"
  },
  {
    id: 6,
    word: "important",
    phonetic: "/ɪmˈpɔːrtənt/",
    partOfSpeech: "adjective",
    definition: "Of great significance or value",
    korean: "중요한",
    example: "It is important to drink enough water every day.",
    exampleKorean: "매일 충분한 물을 마시는 것은 중요해요.",
    synonyms: ["significant", "crucial", "essential"],
    level: "beginner"
  },
  {
    id: 7,
    word: "difficult",
    phonetic: "/ˈdɪfɪkʌlt/",
    partOfSpeech: "adjective",
    definition: "Needing much effort or skill to accomplish",
    korean: "어려운, 힘든",
    example: "Learning a new language can be difficult at first.",
    exampleKorean: "새로운 언어를 배우는 것은 처음에 어려울 수 있어요.",
    synonyms: ["hard", "challenging", "tough"],
    level: "beginner"
  },
  {
    id: 8,
    word: "enjoy",
    phonetic: "/ɪnˈdʒɔɪ/",
    partOfSpeech: "verb",
    definition: "Take delight or pleasure in an activity or occasion",
    korean: "즐기다",
    example: "I enjoy reading books on rainy days.",
    exampleKorean: "저는 비 오는 날 책 읽기를 즐겨요.",
    synonyms: ["relish", "savor", "appreciate"],
    level: "beginner"
  },
  {
    id: 9,
    word: "kind",
    phonetic: "/kaɪnd/",
    partOfSpeech: "adjective",
    definition: "Having a friendly, generous, and considerate nature",
    korean: "친절한, 다정한",
    example: "She was kind enough to help a stranger.",
    exampleKorean: "그녀는 낯선 사람을 도와줄 만큼 친절했어요.",
    synonyms: ["generous", "warm", "caring"],
    level: "beginner"
  },
  {
    id: 10,
    word: "delicious",
    phonetic: "/dɪˈlɪʃəs/",
    partOfSpeech: "adjective",
    definition: "Highly pleasant to the taste",
    korean: "맛있는",
    example: "The food at that restaurant is absolutely delicious.",
    exampleKorean: "그 식당의 음식은 정말 맛있어요.",
    synonyms: ["tasty", "yummy", "flavorful"],
    level: "beginner"
  },
  {
    id: 11,
    word: "music",
    phonetic: "/ˈmjuːzɪk/",
    partOfSpeech: "noun",
    definition: "Vocal or instrumental sounds combined in a way that produces beauty",
    korean: "음악",
    example: "Music can change your mood instantly.",
    exampleKorean: "음악은 당신의 기분을 즉시 바꿀 수 있어요.",
    synonyms: ["melody", "tune", "rhythm"],
    level: "beginner"
  },
  {
    id: 12,
    word: "dream",
    phonetic: "/driːm/",
    partOfSpeech: "noun",
    definition: "A cherished aspiration or ideal",
    korean: "꿈",
    example: "Never give up on your dream.",
    exampleKorean: "당신의 꿈을 절대 포기하지 마세요.",
    synonyms: ["aspiration", "wish", "goal"],
    level: "beginner"
  },
  {
    id: 13,
    word: "nature",
    phonetic: "/ˈneɪtʃər/",
    partOfSpeech: "noun",
    definition: "The phenomena of the physical world including plants, animals, and landscapes",
    korean: "자연",
    example: "Spending time in nature reduces stress.",
    exampleKorean: "자연에서 시간을 보내면 스트레스가 줄어들어요.",
    synonyms: ["environment", "wilderness", "outdoors"],
    level: "beginner"
  },
  {
    id: 14,
    word: "smile",
    phonetic: "/smaɪl/",
    partOfSpeech: "verb",
    definition: "Form one's features into a pleased, kind, or amused expression",
    korean: "미소 짓다",
    example: "He smiled at the little girl playing in the park.",
    exampleKorean: "그는 공원에서 놀고 있는 어린 소녀에게 미소 지었어요.",
    synonyms: ["grin", "beam", "smirk"],
    level: "beginner"
  },
  {
    id: 15,
    word: "health",
    phonetic: "/helθ/",
    partOfSpeech: "noun",
    definition: "The state of being free from illness or injury",
    korean: "건강",
    example: "Good health is more valuable than wealth.",
    exampleKorean: "좋은 건강은 부보다 더 가치 있어요.",
    synonyms: ["wellness", "fitness", "well-being"],
    level: "beginner"
  },
  {
    id: 16,
    word: "simple",
    phonetic: "/ˈsɪmpəl/",
    partOfSpeech: "adjective",
    definition: "Easily understood or done; presenting no difficulty",
    korean: "간단한, 단순한",
    example: "The instructions were simple and easy to follow.",
    exampleKorean: "설명서가 간단하고 따라하기 쉬웠어요.",
    synonyms: ["easy", "basic", "straightforward"],
    level: "beginner"
  },
  {
    id: 17,
    word: "change",
    phonetic: "/tʃeɪndʒ/",
    partOfSpeech: "verb",
    definition: "Make or become different",
    korean: "바꾸다, 변하다",
    example: "You need to change your habits to stay healthy.",
    exampleKorean: "건강을 유지하려면 습관을 바꿔야 해요.",
    synonyms: ["alter", "modify", "transform"],
    level: "beginner"
  },
  {
    id: 18,
    word: "support",
    phonetic: "/səˈpɔːrt/",
    partOfSpeech: "verb",
    definition: "Bear all or part of the weight of; hold up",
    korean: "지지하다, 지원하다",
    example: "Her family always supported her dreams.",
    exampleKorean: "그녀의 가족은 항상 그녀의 꿈을 지지했어요.",
    synonyms: ["help", "assist", "back"],
    level: "beginner"
  },
  {
    id: 19,
    word: "courage",
    phonetic: "/ˈkɜːrɪdʒ/",
    partOfSpeech: "noun",
    definition: "The ability to do something that frightens one; bravery",
    korean: "용기",
    example: "It takes courage to speak up in a crowd.",
    exampleKorean: "군중 앞에서 발언하려면 용기가 필요해요.",
    synonyms: ["bravery", "boldness", "valor"],
    level: "beginner"
  },
  {
    id: 20,
    word: "grow",
    phonetic: "/ɡroʊ/",
    partOfSpeech: "verb",
    definition: "Undergo natural development by increasing in size and changing physically",
    korean: "성장하다, 자라다",
    example: "Plants grow faster in warm weather.",
    exampleKorean: "식물은 따뜻한 날씨에 더 빠르게 자라요.",
    synonyms: ["develop", "expand", "thrive"],
    level: "beginner"
  },
  {
    id: 21,
    word: "choice",
    phonetic: "/tʃɔɪs/",
    partOfSpeech: "noun",
    definition: "An act of selecting or making a decision between options",
    korean: "선택",
    example: "Making the right choice requires careful thought.",
    exampleKorean: "올바른 선택을 하려면 신중한 생각이 필요해요.",
    synonyms: ["option", "decision", "selection"],
    level: "beginner"
  },
  {
    id: 22,
    word: "hope",
    phonetic: "/hoʊp/",
    partOfSpeech: "noun",
    definition: "A feeling of expectation and desire for a certain thing to happen",
    korean: "희망",
    example: "There is always hope for a better tomorrow.",
    exampleKorean: "더 나은 내일에 대한 희망은 항상 있어요.",
    synonyms: ["optimism", "wish", "expectation"],
    level: "beginner"
  },
  {
    id: 23,
    word: "bright",
    phonetic: "/braɪt/",
    partOfSpeech: "adjective",
    definition: "Giving out or reflecting a lot of light; shining",
    korean: "밝은, 빛나는",
    example: "The bright sun made it hard to see.",
    exampleKorean: "밝은 태양이 보기 어렵게 만들었어요.",
    synonyms: ["shining", "brilliant", "radiant"],
    level: "beginner"
  },
  {
    id: 24,
    word: "busy",
    phonetic: "/ˈbɪzi/",
    partOfSpeech: "adjective",
    definition: "Having a great deal to do; not free",
    korean: "바쁜",
    example: "I have been very busy with work this week.",
    exampleKorean: "이번 주는 일로 매우 바빴어요.",
    synonyms: ["occupied", "hectic", "engaged"],
    level: "beginner"
  },
  {
    id: 25,
    word: "share",
    phonetic: "/ʃer/",
    partOfSpeech: "verb",
    definition: "Use or occupy jointly with another or others",
    korean: "나누다, 공유하다",
    example: "She likes to share her food with friends.",
    exampleKorean: "그녀는 친구들과 음식을 나누는 것을 좋아해요.",
    synonyms: ["divide", "split", "distribute"],
    level: "beginner"
  },
  {
    id: 26,
    word: "tired",
    phonetic: "/taɪərd/",
    partOfSpeech: "adjective",
    definition: "In need of sleep or rest; weary",
    korean: "피곤한, 지친",
    example: "After the long hike, everyone was tired.",
    exampleKorean: "긴 하이킹 후 모두가 피곤했어요.",
    synonyms: ["exhausted", "weary", "fatigued"],
    level: "beginner"
  },
  {
    id: 27,
    word: "remember",
    phonetic: "/rɪˈmembər/",
    partOfSpeech: "verb",
    definition: "Have in or be able to bring to one's mind an awareness of something",
    korean: "기억하다",
    example: "I always remember to call my parents on weekends.",
    exampleKorean: "저는 주말에 부모님께 전화하는 것을 항상 기억해요.",
    synonyms: ["recall", "recollect", "retain"],
    level: "beginner"
  },
  {
    id: 28,
    word: "believe",
    phonetic: "/bɪˈliːv/",
    partOfSpeech: "verb",
    definition: "Accept that something is true, especially without proof",
    korean: "믿다",
    example: "You should believe in yourself.",
    exampleKorean: "자기 자신을 믿어야 해요.",
    synonyms: ["trust", "have faith", "accept"],
    level: "beginner"
  },
  {
    id: 29,
    word: "practice",
    phonetic: "/ˈpræktɪs/",
    partOfSpeech: "verb",
    definition: "Perform an activity repeatedly to improve one's proficiency",
    korean: "연습하다",
    example: "You should practice English every day.",
    exampleKorean: "매일 영어를 연습해야 해요.",
    synonyms: ["rehearse", "train", "exercise"],
    level: "beginner"
  },
  {
    id: 30,
    word: "wonderful",
    phonetic: "/ˈwʌndərfʊl/",
    partOfSpeech: "adjective",
    definition: "Inspiring delight, pleasure, or admiration; extremely good",
    korean: "훌륭한, 멋진",
    example: "We had a wonderful time at the beach.",
    exampleKorean: "우리는 해변에서 멋진 시간을 보냈어요.",
    synonyms: ["amazing", "fantastic", "marvelous"],
    level: "beginner"
  },
  {
    id: 31,
    word: "create",
    phonetic: "/kriˈeɪt/",
    partOfSpeech: "verb",
    definition: "Bring something into existence",
    korean: "만들다, 창조하다",
    example: "Artists create beauty out of ordinary materials.",
    exampleKorean: "예술가들은 평범한 재료로 아름다움을 만들어요.",
    synonyms: ["make", "produce", "generate"],
    level: "beginner"
  },
  {
    id: 32,
    word: "success",
    phonetic: "/səkˈses/",
    partOfSpeech: "noun",
    definition: "The accomplishment of an aim or purpose",
    korean: "성공",
    example: "Hard work is the key to success.",
    exampleKorean: "열심히 노력하는 것이 성공의 열쇠예요.",
    synonyms: ["achievement", "triumph", "accomplishment"],
    level: "beginner"
  },
  {
    id: 33,
    word: "peaceful",
    phonetic: "/ˈpiːsfʊl/",
    partOfSpeech: "adjective",
    definition: "Free from disturbance; tranquil",
    korean: "평화로운, 조용한",
    example: "The countryside is very peaceful in the morning.",
    exampleKorean: "아침에 시골은 매우 평화로워요.",
    synonyms: ["calm", "serene", "tranquil"],
    level: "beginner"
  },
  {
    id: 34,
    word: "hungry",
    phonetic: "/ˈhʌŋɡri/",
    partOfSpeech: "adjective",
    definition: "Feeling or displaying the need for food",
    korean: "배고픈",
    example: "I was so hungry I ate two bowls of rice.",
    exampleKorean: "너무 배가 고파서 밥을 두 그릇이나 먹었어요.",
    synonyms: ["starving", "famished", "ravenous"],
    level: "beginner"
  },
  {
    id: 35,
    word: "lucky",
    phonetic: "/ˈlʌki/",
    partOfSpeech: "adjective",
    definition: "Having, bringing, or resulting from good luck",
    korean: "운이 좋은",
    example: "I feel lucky to have such great friends.",
    exampleKorean: "이렇게 좋은 친구들이 있어서 운이 좋다고 느껴요.",
    synonyms: ["fortunate", "blessed", "favored"],
    level: "beginner"
  },
  {
    id: 36,
    word: "curious",
    phonetic: "/ˈkjʊəriəs/",
    partOfSpeech: "adjective",
    definition: "Eager to know or learn something",
    korean: "호기심 많은",
    example: "Children are naturally curious about everything.",
    exampleKorean: "아이들은 모든 것에 대해 자연스럽게 호기심이 많아요.",
    synonyms: ["inquisitive", "eager", "interested"],
    level: "beginner"
  },
  {
    id: 37,
    word: "helpful",
    phonetic: "/ˈhelpfʊl/",
    partOfSpeech: "adjective",
    definition: "Giving or ready to give help",
    korean: "도움이 되는",
    example: "The staff were very helpful and friendly.",
    exampleKorean: "직원들이 매우 도움이 되고 친절했어요.",
    synonyms: ["useful", "supportive", "cooperative"],
    level: "beginner"
  },
  {
    id: 38,
    word: "comfortable",
    phonetic: "/ˈkʌmftərbəl/",
    partOfSpeech: "adjective",
    definition: "Giving physical ease and relaxation",
    korean: "편안한",
    example: "This sofa is very comfortable to sit on.",
    exampleKorean: "이 소파는 앉기에 매우 편안해요.",
    synonyms: ["cozy", "relaxed", "at ease"],
    level: "beginner"
  },
  {
    id: 39,
    word: "excited",
    phonetic: "/ɪkˈsaɪtɪd/",
    partOfSpeech: "adjective",
    definition: "Very enthusiastic and eager",
    korean: "신이 난, 흥분된",
    example: "The children were excited about the field trip.",
    exampleKorean: "아이들은 현장 학습에 신이 났어요.",
    synonyms: ["enthusiastic", "eager", "thrilled"],
    level: "beginner"
  },
  {
    id: 40,
    word: "honest",
    phonetic: "/ˈɒnɪst/",
    partOfSpeech: "adjective",
    definition: "Free of deceit; truthful and sincere",
    korean: "정직한, 솔직한",
    example: "Always be honest with the people you care about.",
    exampleKorean: "당신이 아끼는 사람들에게 항상 정직하세요.",
    synonyms: ["truthful", "sincere", "candid"],
    level: "beginner"
  },

  // ===== INTERMEDIATE (50 words) =====
  {
    id: 41,
    word: "accomplish",
    phonetic: "/əˈkʌmplɪʃ/",
    partOfSpeech: "verb",
    definition: "Achieve or complete successfully",
    korean: "성취하다, 달성하다",
    example: "She accomplished all her goals for the year.",
    exampleKorean: "그녀는 올해 목표를 모두 달성했어요.",
    synonyms: ["achieve", "complete", "fulfill"],
    level: "intermediate"
  },
  {
    id: 42,
    word: "ambition",
    phonetic: "/æmˈbɪʃən/",
    partOfSpeech: "noun",
    definition: "A strong desire to do or to achieve something",
    korean: "야망, 포부",
    example: "His ambition is to become a successful entrepreneur.",
    exampleKorean: "그의 야망은 성공적인 기업가가 되는 것이에요.",
    synonyms: ["aspiration", "drive", "determination"],
    level: "intermediate"
  },
  {
    id: 43,
    word: "analyze",
    phonetic: "/ˈænəlaɪz/",
    partOfSpeech: "verb",
    definition: "Examine methodically and in detail for purposes of explanation and interpretation",
    korean: "분석하다",
    example: "Scientists analyze data to find patterns.",
    exampleKorean: "과학자들은 패턴을 찾기 위해 데이터를 분석해요.",
    synonyms: ["examine", "study", "evaluate"],
    level: "intermediate"
  },
  {
    id: 44,
    word: "appreciate",
    phonetic: "/əˈpriːʃieɪt/",
    partOfSpeech: "verb",
    definition: "Recognize the full worth of; be grateful for",
    korean: "감사하다, 고맙게 여기다",
    example: "I really appreciate your help with this project.",
    exampleKorean: "이 프로젝트에 도움을 주셔서 정말 감사해요.",
    synonyms: ["value", "cherish", "be grateful for"],
    level: "intermediate"
  },
  {
    id: 45,
    word: "challenge",
    phonetic: "/ˈtʃælɪndʒ/",
    partOfSpeech: "noun",
    definition: "A task or situation that tests someone's abilities",
    korean: "도전, 어려운 과제",
    example: "Every challenge is an opportunity to grow.",
    exampleKorean: "모든 도전은 성장할 기회예요.",
    synonyms: ["difficulty", "obstacle", "test"],
    level: "intermediate"
  },
  {
    id: 46,
    word: "confident",
    phonetic: "/ˈkɒnfɪdənt/",
    partOfSpeech: "adjective",
    definition: "Feeling or showing certainty about something",
    korean: "자신감 있는",
    example: "Be confident when presenting your ideas.",
    exampleKorean: "아이디어를 발표할 때 자신감을 가지세요.",
    synonyms: ["self-assured", "bold", "certain"],
    level: "intermediate"
  },
  {
    id: 47,
    word: "consequence",
    phonetic: "/ˈkɒnsɪkwəns/",
    partOfSpeech: "noun",
    definition: "A result or effect of an action or condition",
    korean: "결과, 영향",
    example: "Every decision has consequences, good or bad.",
    exampleKorean: "모든 결정에는 좋든 나쁘든 결과가 있어요.",
    synonyms: ["result", "outcome", "effect"],
    level: "intermediate"
  },
  {
    id: 48,
    word: "contribute",
    phonetic: "/kənˈtrɪbjuːt/",
    partOfSpeech: "verb",
    definition: "Give something in order to help achieve or provide something",
    korean: "기여하다, 공헌하다",
    example: "Everyone can contribute to making the world better.",
    exampleKorean: "모든 사람이 세상을 더 나은 곳으로 만드는 데 기여할 수 있어요.",
    synonyms: ["donate", "give", "add"],
    level: "intermediate"
  },
  {
    id: 49,
    word: "critical",
    phonetic: "/ˈkrɪtɪkəl/",
    partOfSpeech: "adjective",
    definition: "Expressing or involving an analysis of the merits and faults",
    korean: "비판적인, 중요한",
    example: "Critical thinking is an essential skill in modern life.",
    exampleKorean: "비판적 사고는 현대 생활에서 필수적인 기술이에요.",
    synonyms: ["analytical", "evaluative", "crucial"],
    level: "intermediate"
  },
  {
    id: 50,
    word: "dedicate",
    phonetic: "/ˈdedɪkeɪt/",
    partOfSpeech: "verb",
    definition: "Devote time or effort to a particular task or purpose",
    korean: "헌신하다, 전념하다",
    example: "She dedicated her life to helping others.",
    exampleKorean: "그녀는 남을 돕는 데 일생을 헌신했어요.",
    synonyms: ["commit", "devote", "consecrate"],
    level: "intermediate"
  },
  {
    id: 51,
    word: "demonstrate",
    phonetic: "/ˈdemənstreɪt/",
    partOfSpeech: "verb",
    definition: "Clearly show the existence or truth of something by giving proof or evidence",
    korean: "보여주다, 증명하다",
    example: "She demonstrated how to use the software.",
    exampleKorean: "그녀는 소프트웨어 사용 방법을 보여줬어요.",
    synonyms: ["show", "prove", "illustrate"],
    level: "intermediate"
  },
  {
    id: 52,
    word: "efficient",
    phonetic: "/ɪˈfɪʃənt/",
    partOfSpeech: "adjective",
    definition: "Achieving maximum productivity with minimum effort",
    korean: "효율적인",
    example: "Working efficiently helps you finish tasks faster.",
    exampleKorean: "효율적으로 일하면 작업을 더 빨리 끝낼 수 있어요.",
    synonyms: ["productive", "effective", "streamlined"],
    level: "intermediate"
  },
  {
    id: 53,
    word: "emphasize",
    phonetic: "/ˈemfəsaɪz/",
    partOfSpeech: "verb",
    definition: "Give special importance or value to something in speaking or writing",
    korean: "강조하다",
    example: "The teacher emphasized the importance of reading daily.",
    exampleKorean: "선생님은 매일 독서의 중요성을 강조했어요.",
    synonyms: ["stress", "highlight", "underline"],
    level: "intermediate"
  },
  {
    id: 54,
    word: "flexible",
    phonetic: "/ˈfleksɪbəl/",
    partOfSpeech: "adjective",
    definition: "Willing to change or compromise; able to bend without breaking",
    korean: "유연한",
    example: "A flexible schedule allows for a better work-life balance.",
    exampleKorean: "유연한 일정은 더 나은 일과 생활의 균형을 가능하게 해요.",
    synonyms: ["adaptable", "versatile", "accommodating"],
    level: "intermediate"
  },
  {
    id: 55,
    word: "genuine",
    phonetic: "/ˈdʒenjuɪn/",
    partOfSpeech: "adjective",
    definition: "Truly what something is said to be; authentic",
    korean: "진정한, 진실한",
    example: "A genuine smile is impossible to fake.",
    exampleKorean: "진정한 미소는 흉내 낼 수 없어요.",
    synonyms: ["authentic", "real", "sincere"],
    level: "intermediate"
  },
  {
    id: 56,
    word: "gradual",
    phonetic: "/ˈɡrædʒuəl/",
    partOfSpeech: "adjective",
    definition: "Taking place or progressing slowly or by degrees",
    korean: "점진적인, 서서히",
    example: "There was a gradual improvement in her health.",
    exampleKorean: "그녀의 건강이 점진적으로 좋아졌어요.",
    synonyms: ["slow", "steady", "incremental"],
    level: "intermediate"
  },
  {
    id: 57,
    word: "influence",
    phonetic: "/ˈɪnfluəns/",
    partOfSpeech: "noun",
    definition: "The capacity to have an effect on the character or behavior of someone",
    korean: "영향, 영향력",
    example: "Good teachers have a lasting influence on their students.",
    exampleKorean: "좋은 선생님은 학생들에게 지속적인 영향을 미쳐요.",
    synonyms: ["impact", "effect", "sway"],
    level: "intermediate"
  },
  {
    id: 58,
    word: "innovative",
    phonetic: "/ˈɪnəveɪtɪv/",
    partOfSpeech: "adjective",
    definition: "Featuring new methods; advanced and original",
    korean: "혁신적인",
    example: "The company launched an innovative product this year.",
    exampleKorean: "그 회사는 올해 혁신적인 제품을 출시했어요.",
    synonyms: ["creative", "original", "pioneering"],
    level: "intermediate"
  },
  {
    id: 59,
    word: "motivate",
    phonetic: "/ˈmoʊtɪveɪt/",
    partOfSpeech: "verb",
    definition: "Provide someone with a reason for doing something",
    korean: "동기를 부여하다",
    example: "A good leader knows how to motivate their team.",
    exampleKorean: "좋은 리더는 팀에 동기를 부여하는 방법을 알아요.",
    synonyms: ["inspire", "encourage", "drive"],
    level: "intermediate"
  },
  {
    id: 60,
    word: "negotiate",
    phonetic: "/nɪˈɡoʊʃieɪt/",
    partOfSpeech: "verb",
    definition: "Obtain or bring about by discussion",
    korean: "협상하다",
    example: "They negotiated a fair price for the product.",
    exampleKorean: "그들은 제품에 대한 공정한 가격을 협상했어요.",
    synonyms: ["bargain", "discuss", "compromise"],
    level: "intermediate"
  },
  {
    id: 61,
    word: "persistent",
    phonetic: "/pərˈsɪstənt/",
    partOfSpeech: "adjective",
    definition: "Continuing firmly despite difficulty or opposition",
    korean: "끈질긴, 지속적인",
    example: "Persistent effort leads to success in the end.",
    exampleKorean: "끈질긴 노력은 결국 성공으로 이어져요.",
    synonyms: ["determined", "tenacious", "relentless"],
    level: "intermediate"
  },
  {
    id: 62,
    word: "persuade",
    phonetic: "/pərˈsweɪd/",
    partOfSpeech: "verb",
    definition: "Cause someone to do something through reasoning or argument",
    korean: "설득하다",
    example: "She tried to persuade him to join the club.",
    exampleKorean: "그녀는 그에게 클럽에 가입하도록 설득하려 했어요.",
    synonyms: ["convince", "influence", "sway"],
    level: "intermediate"
  },
  {
    id: 63,
    word: "prioritize",
    phonetic: "/praɪˈɒrɪtaɪz/",
    partOfSpeech: "verb",
    definition: "Designate or treat something as more important than other things",
    korean: "우선순위를 정하다",
    example: "You need to prioritize your tasks to be productive.",
    exampleKorean: "생산적이 되려면 작업의 우선순위를 정해야 해요.",
    synonyms: ["rank", "order", "focus on"],
    level: "intermediate"
  },
  {
    id: 64,
    word: "productive",
    phonetic: "/prəˈdʌktɪv/",
    partOfSpeech: "adjective",
    definition: "Producing or able to produce large amounts of goods or results",
    korean: "생산적인",
    example: "A good night's sleep makes you more productive.",
    exampleKorean: "충분한 수면은 당신을 더 생산적으로 만들어요.",
    synonyms: ["efficient", "effective", "fruitful"],
    level: "intermediate"
  },
  {
    id: 65,
    word: "reliable",
    phonetic: "/rɪˈlaɪəbəl/",
    partOfSpeech: "adjective",
    definition: "Consistently good in quality or performance; able to be trusted",
    korean: "믿을 수 있는, 신뢰할 수 있는",
    example: "A reliable employee shows up on time every day.",
    exampleKorean: "믿을 수 있는 직원은 매일 제시간에 출근해요.",
    synonyms: ["dependable", "trustworthy", "consistent"],
    level: "intermediate"
  },
  {
    id: 66,
    word: "significant",
    phonetic: "/sɪɡˈnɪfɪkənt/",
    partOfSpeech: "adjective",
    definition: "Sufficiently great or important to be worthy of attention",
    korean: "중요한, 상당한",
    example: "There was a significant increase in sales last quarter.",
    exampleKorean: "지난 분기에 매출이 크게 증가했어요.",
    synonyms: ["important", "notable", "considerable"],
    level: "intermediate"
  },
  {
    id: 67,
    word: "sophisticated",
    phonetic: "/səˈfɪstɪkeɪtɪd/",
    partOfSpeech: "adjective",
    definition: "Having a refined knowledge of the world; complex or advanced",
    korean: "세련된, 정교한",
    example: "The software has a sophisticated design.",
    exampleKorean: "그 소프트웨어는 정교한 디자인을 가지고 있어요.",
    synonyms: ["refined", "complex", "advanced"],
    level: "intermediate"
  },
  {
    id: 68,
    word: "tolerate",
    phonetic: "/ˈtɒləreɪt/",
    partOfSpeech: "verb",
    definition: "Allow the existence of something without interference",
    korean: "참다, 허용하다",
    example: "It is important to tolerate different viewpoints.",
    exampleKorean: "다른 관점을 허용하는 것이 중요해요.",
    synonyms: ["endure", "accept", "bear"],
    level: "intermediate"
  },
  {
    id: 69,
    word: "transform",
    phonetic: "/trænsˈfɔːrm/",
    partOfSpeech: "verb",
    definition: "Make a thorough or dramatic change in form, appearance, or character",
    korean: "변화시키다, 변형하다",
    example: "Exercise can transform your body and mind.",
    exampleKorean: "운동은 몸과 마음을 변화시킬 수 있어요.",
    synonyms: ["change", "alter", "convert"],
    level: "intermediate"
  },
  {
    id: 70,
    word: "unique",
    phonetic: "/juːˈniːk/",
    partOfSpeech: "adjective",
    definition: "Being the only one of its kind; unlike anything else",
    korean: "독특한, 유일한",
    example: "Every person has a unique fingerprint.",
    exampleKorean: "모든 사람은 독특한 지문을 가지고 있어요.",
    synonyms: ["one-of-a-kind", "distinctive", "singular"],
    level: "intermediate"
  },
  {
    id: 71,
    word: "opportunity",
    phonetic: "/ˌɒpəˈtjuːnɪti/",
    partOfSpeech: "noun",
    definition: "A set of circumstances that makes it possible to do something",
    korean: "기회",
    example: "Never miss an opportunity to learn something new.",
    exampleKorean: "새로운 것을 배울 기회를 절대 놓치지 마세요.",
    synonyms: ["chance", "opening", "occasion"],
    level: "intermediate"
  },
  {
    id: 72,
    word: "passionate",
    phonetic: "/ˈpæʃənɪt/",
    partOfSpeech: "adjective",
    definition: "Having, showing, or caused by strong feelings",
    korean: "열정적인",
    example: "She is passionate about protecting the environment.",
    exampleKorean: "그녀는 환경 보호에 열정적이에요.",
    synonyms: ["enthusiastic", "fervent", "ardent"],
    level: "intermediate"
  },
  {
    id: 73,
    word: "responsibility",
    phonetic: "/rɪˌspɒnsəˈbɪlɪti/",
    partOfSpeech: "noun",
    definition: "The state of being accountable for something within one's power",
    korean: "책임, 의무",
    example: "Taking responsibility for your actions is a sign of maturity.",
    exampleKorean: "자신의 행동에 책임을 지는 것은 성숙함의 표시예요.",
    synonyms: ["duty", "obligation", "accountability"],
    level: "intermediate"
  },
  {
    id: 74,
    word: "resilient",
    phonetic: "/rɪˈzɪliənt/",
    partOfSpeech: "adjective",
    definition: "Able to withstand or recover quickly from difficult conditions",
    korean: "회복력 있는, 탄력적인",
    example: "Resilient people bounce back from failure quickly.",
    exampleKorean: "회복력 있는 사람들은 실패에서 빠르게 회복해요.",
    synonyms: ["tough", "adaptable", "strong"],
    level: "intermediate"
  },
  {
    id: 75,
    word: "perspective",
    phonetic: "/pərˈspektɪv/",
    partOfSpeech: "noun",
    definition: "A particular attitude toward or way of regarding something",
    korean: "관점, 시각",
    example: "Traveling gives you a new perspective on life.",
    exampleKorean: "여행은 삶에 대한 새로운 관점을 줘요.",
    synonyms: ["viewpoint", "outlook", "standpoint"],
    level: "intermediate"
  },
  {
    id: 76,
    word: "consistent",
    phonetic: "/kənˈsɪstənt/",
    partOfSpeech: "adjective",
    definition: "Acting or done in the same way over time",
    korean: "일관된, 꾸준한",
    example: "Consistent practice is the key to mastering any skill.",
    exampleKorean: "꾸준한 연습이 어떤 기술을 마스터하는 핵심이에요.",
    synonyms: ["steady", "reliable", "uniform"],
    level: "intermediate"
  },
  {
    id: 77,
    word: "collaborate",
    phonetic: "/kəˈlæbəreɪt/",
    partOfSpeech: "verb",
    definition: "Work jointly on an activity or project",
    korean: "협력하다, 공동 작업하다",
    example: "The two companies collaborated on a new product.",
    exampleKorean: "두 회사는 새 제품 개발에 협력했어요.",
    synonyms: ["cooperate", "partner", "work together"],
    level: "intermediate"
  },
  {
    id: 78,
    word: "discipline",
    phonetic: "/ˈdɪsɪplɪn/",
    partOfSpeech: "noun",
    definition: "The practice of training yourself to obey rules or a code of behavior",
    korean: "규율, 자제력",
    example: "Self-discipline is essential for long-term success.",
    exampleKorean: "자기 규율은 장기적인 성공을 위해 필수적이에요.",
    synonyms: ["self-control", "order", "rigor"],
    level: "intermediate"
  },
  {
    id: 79,
    word: "empathy",
    phonetic: "/ˈempəθi/",
    partOfSpeech: "noun",
    definition: "The ability to understand and share the feelings of another",
    korean: "공감, 감정 이입",
    example: "Empathy helps build stronger relationships.",
    exampleKorean: "공감은 더 강한 관계를 구축하는 데 도움이 돼요.",
    synonyms: ["compassion", "understanding", "sensitivity"],
    level: "intermediate"
  },
  {
    id: 80,
    word: "potential",
    phonetic: "/pəˈtenʃəl/",
    partOfSpeech: "noun",
    definition: "Latent qualities or abilities that may be developed",
    korean: "잠재력, 가능성",
    example: "Every child has the potential to succeed.",
    exampleKorean: "모든 아이는 성공할 잠재력이 있어요.",
    synonyms: ["capability", "ability", "promise"],
    level: "intermediate"
  },
  {
    id: 81,
    word: "strategy",
    phonetic: "/ˈstrætɪdʒi/",
    partOfSpeech: "noun",
    definition: "A plan of action designed to achieve a long-term aim",
    korean: "전략",
    example: "You need a clear strategy to achieve your goals.",
    exampleKorean: "목표를 달성하려면 명확한 전략이 필요해요.",
    synonyms: ["plan", "approach", "method"],
    level: "intermediate"
  },
  {
    id: 82,
    word: "sustainable",
    phonetic: "/səˈsteɪnəbəl/",
    partOfSpeech: "adjective",
    definition: "Able to be maintained at a certain rate or level without exhausting resources",
    korean: "지속 가능한",
    example: "We need sustainable solutions to environmental problems.",
    exampleKorean: "우리는 환경 문제에 대한 지속 가능한 해결책이 필요해요.",
    synonyms: ["maintainable", "viable", "eco-friendly"],
    level: "intermediate"
  },
  {
    id: 83,
    word: "acknowledge",
    phonetic: "/əkˈnɒlɪdʒ/",
    partOfSpeech: "verb",
    definition: "Accept or admit the existence or truth of something",
    korean: "인정하다, 인식하다",
    example: "He acknowledged his mistake and apologized.",
    exampleKorean: "그는 자신의 실수를 인정하고 사과했어요.",
    synonyms: ["recognize", "admit", "accept"],
    level: "intermediate"
  },
  {
    id: 84,
    word: "adapt",
    phonetic: "/əˈdæpt/",
    partOfSpeech: "verb",
    definition: "Become adjusted to new conditions",
    korean: "적응하다",
    example: "Humans have the ability to adapt to almost any environment.",
    exampleKorean: "인간은 거의 어떤 환경에도 적응할 수 있는 능력이 있어요.",
    synonyms: ["adjust", "acclimate", "conform"],
    level: "intermediate"
  },
  {
    id: 85,
    word: "balance",
    phonetic: "/ˈbæləns/",
    partOfSpeech: "noun",
    definition: "A condition in which different elements are equal or in the correct proportions",
    korean: "균형",
    example: "Finding a balance between work and rest is important.",
    exampleKorean: "일과 휴식 사이의 균형을 찾는 것이 중요해요.",
    synonyms: ["equilibrium", "stability", "harmony"],
    level: "intermediate"
  },
  {
    id: 86,
    word: "commitment",
    phonetic: "/kəˈmɪtmənt/",
    partOfSpeech: "noun",
    definition: "The state or quality of being dedicated to a cause or activity",
    korean: "헌신, 약속",
    example: "Her commitment to the project impressed everyone.",
    exampleKorean: "프로젝트에 대한 그녀의 헌신은 모두를 감동시켰어요.",
    synonyms: ["dedication", "loyalty", "devotion"],
    level: "intermediate"
  },
  {
    id: 87,
    word: "enhance",
    phonetic: "/ɪnˈhæns/",
    partOfSpeech: "verb",
    definition: "Intensify, increase, or further improve the quality or value of something",
    korean: "향상시키다, 강화하다",
    example: "Regular exercise can enhance your mental health.",
    exampleKorean: "규칙적인 운동은 정신 건강을 향상시킬 수 있어요.",
    synonyms: ["improve", "boost", "strengthen"],
    level: "intermediate"
  },
  {
    id: 88,
    word: "fundamental",
    phonetic: "/ˌfʌndəˈmentəl/",
    partOfSpeech: "adjective",
    definition: "Forming a necessary base or core; of central importance",
    korean: "근본적인, 기본적인",
    example: "Understanding grammar is fundamental to learning a language.",
    exampleKorean: "문법을 이해하는 것은 언어를 배우는 데 근본적이에요.",
    synonyms: ["basic", "essential", "core"],
    level: "intermediate"
  },
  {
    id: 89,
    word: "integrity",
    phonetic: "/ɪnˈteɡrɪti/",
    partOfSpeech: "noun",
    definition: "The quality of being honest and having strong moral principles",
    korean: "성실, 청렴함",
    example: "Leaders must act with integrity to earn trust.",
    exampleKorean: "리더는 신뢰를 얻기 위해 성실하게 행동해야 해요.",
    synonyms: ["honesty", "virtue", "ethics"],
    level: "intermediate"
  },
  {
    id: 90,
    word: "innovative",
    phonetic: "/ˈɪnəvətɪv/",
    partOfSpeech: "adjective",
    definition: "Introducing new ideas; original and creative in thinking",
    korean: "혁신적인, 창의적인",
    example: "The team came up with an innovative solution to the problem.",
    exampleKorean: "팀은 문제에 대한 혁신적인 해결책을 제시했어요.",
    synonyms: ["creative", "original", "pioneering"],
    level: "intermediate"
  },

  // ===== ADVANCED (30 words) =====
  {
    id: 91,
    word: "serendipity",
    phonetic: "/ˌserənˈdɪpɪti/",
    partOfSpeech: "noun",
    definition: "The occurrence of events by chance in a happy or beneficial way",
    korean: "뜻밖의 행운, 우연한 좋은 발견",
    example: "Meeting my business partner was pure serendipity.",
    exampleKorean: "비즈니스 파트너를 만난 것은 순전한 행운이었어요.",
    synonyms: ["luck", "fortune", "happy chance"],
    level: "advanced"
  },
  {
    id: 92,
    word: "ephemeral",
    phonetic: "/ɪˈfemərəl/",
    partOfSpeech: "adjective",
    definition: "Lasting for a very short time",
    korean: "덧없는, 일시적인",
    example: "Fame is ephemeral, but character lasts forever.",
    exampleKorean: "명성은 덧없지만 인품은 영원히 지속돼요.",
    synonyms: ["transient", "fleeting", "momentary"],
    level: "advanced"
  },
  {
    id: 93,
    word: "eloquent",
    phonetic: "/ˈeləkwənt/",
    partOfSpeech: "adjective",
    definition: "Fluent or persuasive in speaking or writing",
    korean: "웅변적인, 유창한",
    example: "Her eloquent speech moved the entire audience.",
    exampleKorean: "그녀의 웅변적인 연설은 청중 전체를 감동시켰어요.",
    synonyms: ["articulate", "expressive", "persuasive"],
    level: "advanced"
  },
  {
    id: 94,
    word: "intrinsic",
    phonetic: "/ɪnˈtrɪnsɪk/",
    partOfSpeech: "adjective",
    definition: "Belonging naturally; essential; inherent",
    korean: "본질적인, 내재적인",
    example: "The intrinsic value of knowledge cannot be measured.",
    exampleKorean: "지식의 본질적인 가치는 측정할 수 없어요.",
    synonyms: ["inherent", "fundamental", "innate"],
    level: "advanced"
  },
  {
    id: 95,
    word: "paradox",
    phonetic: "/ˈpærədɒks/",
    partOfSpeech: "noun",
    definition: "A seemingly absurd or self-contradictory statement that may be true",
    korean: "역설, 모순",
    example: "It's a paradox that staying still can sometimes move you forward.",
    exampleKorean: "가만히 있는 것이 때로는 앞으로 나아가게 한다는 것은 역설이에요.",
    synonyms: ["contradiction", "irony", "puzzle"],
    level: "advanced"
  },
  {
    id: 96,
    word: "meticulous",
    phonetic: "/məˈtɪkjʊləs/",
    partOfSpeech: "adjective",
    definition: "Showing great attention to detail or being very careful and precise",
    korean: "꼼꼼한, 세심한",
    example: "She was meticulous in her research.",
    exampleKorean: "그녀는 연구에서 매우 꼼꼼했어요.",
    synonyms: ["precise", "thorough", "scrupulous"],
    level: "advanced"
  },
  {
    id: 97,
    word: "tenacious",
    phonetic: "/tɪˈneɪʃəs/",
    partOfSpeech: "adjective",
    definition: "Tending to keep a firm hold of something; clinging or adhering closely",
    korean: "끈질긴, 완고한",
    example: "Her tenacious spirit helped her overcome every obstacle.",
    exampleKorean: "그녀의 끈질긴 정신은 모든 장애물을 극복하는 데 도움이 됐어요.",
    synonyms: ["persistent", "determined", "stubborn"],
    level: "advanced"
  },
  {
    id: 98,
    word: "profound",
    phonetic: "/prəˈfaʊnd/",
    partOfSpeech: "adjective",
    definition: "Very great or intense; having deep meaning",
    korean: "심오한, 깊은",
    example: "The book had a profound impact on my thinking.",
    exampleKorean: "그 책은 내 사고에 심오한 영향을 미쳤어요.",
    synonyms: ["deep", "significant", "insightful"],
    level: "advanced"
  },
  {
    id: 99,
    word: "pragmatic",
    phonetic: "/præɡˈmætɪk/",
    partOfSpeech: "adjective",
    definition: "Dealing with things sensibly and realistically in a practical way",
    korean: "실용적인, 현실적인",
    example: "A pragmatic approach works better than idealism in business.",
    exampleKorean: "사업에서는 이상주의보다 실용적인 접근 방식이 더 효과적이에요.",
    synonyms: ["practical", "realistic", "sensible"],
    level: "advanced"
  },
  {
    id: 100,
    word: "ambiguous",
    phonetic: "/æmˈbɪɡjuəs/",
    partOfSpeech: "adjective",
    definition: "Open to more than one interpretation; not having one obvious meaning",
    korean: "애매한, 모호한",
    example: "His ambiguous answer left everyone confused.",
    exampleKorean: "그의 애매한 대답은 모두를 혼란스럽게 했어요.",
    synonyms: ["vague", "unclear", "equivocal"],
    level: "advanced"
  },
  {
    id: 101,
    word: "benevolent",
    phonetic: "/bəˈnevələnt/",
    partOfSpeech: "adjective",
    definition: "Well meaning and kindly; generous or helpful",
    korean: "자비로운, 친절한",
    example: "A benevolent leader cares for the needs of all people.",
    exampleKorean: "자비로운 리더는 모든 사람의 필요를 돌봐요.",
    synonyms: ["kind", "generous", "charitable"],
    level: "advanced"
  },
  {
    id: 102,
    word: "cogent",
    phonetic: "/ˈkoʊdʒənt/",
    partOfSpeech: "adjective",
    definition: "Clear, logical, and convincing",
    korean: "설득력 있는, 명쾌한",
    example: "She made a cogent argument for the policy change.",
    exampleKorean: "그녀는 정책 변경에 대한 설득력 있는 주장을 펼쳤어요.",
    synonyms: ["compelling", "persuasive", "logical"],
    level: "advanced"
  },
  {
    id: 103,
    word: "diligent",
    phonetic: "/ˈdɪlɪdʒənt/",
    partOfSpeech: "adjective",
    definition: "Having or showing care and conscientiousness in one's work",
    korean: "부지런한, 성실한",
    example: "Diligent students consistently achieve better grades.",
    exampleKorean: "부지런한 학생들은 일관되게 더 나은 성적을 받아요.",
    synonyms: ["hardworking", "industrious", "conscientious"],
    level: "advanced"
  },
  {
    id: 104,
    word: "erudite",
    phonetic: "/ˈerjʊdaɪt/",
    partOfSpeech: "adjective",
    definition: "Having or showing great knowledge or learning",
    korean: "박식한, 학식 있는",
    example: "The professor was known for being highly erudite.",
    exampleKorean: "그 교수는 매우 박식한 것으로 알려져 있었어요.",
    synonyms: ["learned", "knowledgeable", "scholarly"],
    level: "advanced"
  },
  {
    id: 105,
    word: "fortitude",
    phonetic: "/ˈfɔːrtɪtjuːd/",
    partOfSpeech: "noun",
    definition: "Courage in pain or adversity",
    korean: "불굴의 정신, 용기",
    example: "She faced her illness with remarkable fortitude.",
    exampleKorean: "그녀는 놀라운 불굴의 정신으로 병에 맞섰어요.",
    synonyms: ["endurance", "resilience", "bravery"],
    level: "advanced"
  },
  {
    id: 106,
    word: "gregarious",
    phonetic: "/ɡrɪˈɡeəriəs/",
    partOfSpeech: "adjective",
    definition: "Fond of company; sociable",
    korean: "사교적인, 무리를 좋아하는",
    example: "Her gregarious nature made her popular at parties.",
    exampleKorean: "그녀의 사교적인 성격이 파티에서 인기를 끌었어요.",
    synonyms: ["sociable", "outgoing", "extroverted"],
    level: "advanced"
  },
  {
    id: 107,
    word: "incongruous",
    phonetic: "/ɪnˈkɒŋɡruəs/",
    partOfSpeech: "adjective",
    definition: "Not in harmony or keeping with the surroundings or other aspects",
    korean: "어울리지 않는, 부조화한",
    example: "The modern building looked incongruous in the ancient village.",
    exampleKorean: "현대적인 건물이 고대 마을에서 어울리지 않아 보였어요.",
    synonyms: ["out of place", "inconsistent", "inappropriate"],
    level: "advanced"
  },
  {
    id: 108,
    word: "lucid",
    phonetic: "/ˈluːsɪd/",
    partOfSpeech: "adjective",
    definition: "Expressed clearly; easy to understand",
    korean: "명쾌한, 명확한",
    example: "His lucid explanation made the complex topic easy to grasp.",
    exampleKorean: "그의 명쾌한 설명이 복잡한 주제를 쉽게 이해하게 했어요.",
    synonyms: ["clear", "coherent", "intelligible"],
    level: "advanced"
  },
  {
    id: 109,
    word: "magnanimous",
    phonetic: "/mæɡˈnænɪməs/",
    partOfSpeech: "adjective",
    definition: "Very generous or forgiving, especially toward a rival or enemy",
    korean: "관대한, 아량이 넓은",
    example: "It was magnanimous of him to forgive those who had wronged him.",
    exampleKorean: "자신을 해친 사람들을 용서한 것은 관대한 행동이었어요.",
    synonyms: ["generous", "forgiving", "noble"],
    level: "advanced"
  },
  {
    id: 110,
    word: "nuanced",
    phonetic: "/ˈnjuːɑːnst/",
    partOfSpeech: "adjective",
    definition: "Characterized by subtle shades of meaning or expression",
    korean: "미묘한, 뉘앙스가 있는",
    example: "The author's nuanced portrayal of the characters was impressive.",
    exampleKorean: "작가의 등장인물에 대한 미묘한 묘사가 인상적이었어요.",
    synonyms: ["subtle", "complex", "layered"],
    level: "advanced"
  },
  {
    id: 111,
    word: "ostentatious",
    phonetic: "/ˌɒstənˈteɪʃəs/",
    partOfSpeech: "adjective",
    definition: "Characterized by vulgar or pretentious display; designed to impress",
    korean: "과시적인, 허세 부리는",
    example: "His ostentatious lifestyle attracted attention wherever he went.",
    exampleKorean: "그의 과시적인 생활 방식은 그가 가는 곳마다 주목을 끌었어요.",
    synonyms: ["showy", "pretentious", "flamboyant"],
    level: "advanced"
  },
  {
    id: 112,
    word: "pernicious",
    phonetic: "/pəˈnɪʃəs/",
    partOfSpeech: "adjective",
    definition: "Having a harmful effect, especially in a gradual or subtle way",
    korean: "해로운, 유해한",
    example: "Social media can have a pernicious effect on self-esteem.",
    exampleKorean: "소셜 미디어는 자존감에 해로운 영향을 미칠 수 있어요.",
    synonyms: ["harmful", "destructive", "damaging"],
    level: "advanced"
  },
  {
    id: 113,
    word: "quintessential",
    phonetic: "/ˌkwɪntɪˈsenʃəl/",
    partOfSpeech: "adjective",
    definition: "Representing the most perfect or typical example of a quality or class",
    korean: "전형적인, 가장 순수한",
    example: "He is the quintessential example of a self-made man.",
    exampleKorean: "그는 자수성가한 사람의 전형적인 예예요.",
    synonyms: ["typical", "classic", "archetypal"],
    level: "advanced"
  },
  {
    id: 114,
    word: "recalcitrant",
    phonetic: "/rɪˈkælsɪtrənt/",
    partOfSpeech: "adjective",
    definition: "Having an obstinately uncooperative attitude toward authority",
    korean: "반항적인, 고집스러운",
    example: "The recalcitrant student refused to follow the school rules.",
    exampleKorean: "반항적인 학생은 학교 규칙을 따르기를 거부했어요.",
    synonyms: ["defiant", "stubborn", "unruly"],
    level: "advanced"
  },
  {
    id: 115,
    word: "sagacious",
    phonetic: "/səˈɡeɪʃəs/",
    partOfSpeech: "adjective",
    definition: "Having or showing keen mental discernment and good judgment",
    korean: "현명한, 명민한",
    example: "The sagacious old leader guided the nation through the crisis.",
    exampleKorean: "현명한 노 지도자는 위기 속에서 국가를 이끌었어요.",
    synonyms: ["wise", "perceptive", "shrewd"],
    level: "advanced"
  },
  {
    id: 116,
    word: "ubiquitous",
    phonetic: "/juːˈbɪkwɪtəs/",
    partOfSpeech: "adjective",
    definition: "Present, appearing, or found everywhere",
    korean: "어디에나 있는, 편재하는",
    example: "Smartphones have become ubiquitous in modern society.",
    exampleKorean: "스마트폰은 현대 사회에서 어디에나 있게 되었어요.",
    synonyms: ["omnipresent", "pervasive", "widespread"],
    level: "advanced"
  },
  {
    id: 117,
    word: "verisimilitude",
    phonetic: "/ˌverɪsɪˈmɪlɪtjuːd/",
    partOfSpeech: "noun",
    definition: "The appearance of being true or real",
    korean: "그럴듯함, 진실다움",
    example: "The film's historical verisimilitude impressed critics.",
    exampleKorean: "영화의 역사적 사실감이 비평가들을 감동시켰어요.",
    synonyms: ["realism", "authenticity", "plausibility"],
    level: "advanced"
  },
  {
    id: 118,
    word: "xenophilia",
    phonetic: "/ˌzenəˈfɪliə/",
    partOfSpeech: "noun",
    definition: "A love of foreign cultures and customs",
    korean: "외국 문화에 대한 사랑",
    example: "Her xenophilia made her eager to try foods from all over the world.",
    exampleKorean: "그녀의 외국 문화에 대한 사랑이 세계 각지의 음식을 먹고 싶게 만들었어요.",
    synonyms: ["cosmopolitanism", "open-mindedness", "cultural curiosity"],
    level: "advanced"
  },
  {
    id: 119,
    word: "zealous",
    phonetic: "/ˈzeləs/",
    partOfSpeech: "adjective",
    definition: "Having or showing great energy or enthusiasm in pursuit of a cause",
    korean: "열성적인, 열정적인",
    example: "She was a zealous advocate for environmental protection.",
    exampleKorean: "그녀는 환경 보호를 위한 열성적인 지지자였어요.",
    synonyms: ["passionate", "enthusiastic", "fervent"],
    level: "advanced"
  },
  {
    id: 120,
    word: "equanimity",
    phonetic: "/ˌiːkwəˈnɪmɪti/",
    partOfSpeech: "noun",
    definition: "Mental calmness, composure, and evenness of temper, especially in difficult situations",
    korean: "평정심, 침착함",
    example: "She faced every challenge with remarkable equanimity.",
    exampleKorean: "그녀는 모든 도전을 놀라운 평정심으로 맞이했어요.",
    synonyms: ["composure", "calmness", "serenity"],
    level: "advanced"
  }
];
